<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>f8d5567f-62c6-4c9d-b43b-29e0f571cba2</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bookify.Application\Bookify.Application.csproj" />
      <ProjectReference Include="..\Bookify.Infrastructure\Bookify.Infrastructure.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Booking.IntegrationEvents\Bookify.Modules.Booking.IntegrationEvents.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Notifications.Application\Bookify.Modules.Notifications.Application.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Notifications.Infrastructure\Bookify.Modules.Notifications.Infrastructure.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Scheduling.Application\Bookify.Modules.Scheduling.Application.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Scheduling.Infrastructure\Bookify.Modules.Scheduling.Infrastructure.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Users.Application\Bookify.Modules.Users.Application.csproj" />
      <ProjectReference Include="..\Bookify.Modules.Users.Infrastructure\Bookify.Modules.Users.Infrastructure.csproj" />
    </ItemGroup>

</Project>
